<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Suprema.Core\Suprema.Core.csproj" />
    <ProjectReference Include="..\Suprema.Content\Suprema.Content.csproj" />
  </ItemGroup>

  <ItemGroup>

  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
